services:
  reverse-proxy:
    image: traefik:v3.2.2
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:80 --entryPoints.websecure.address=:443 --log.level=PANIC
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: size-server
    labels:
      - traefik.http.routers.backend.rule=Host(`size.docker.localhost`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=8080
      - traefik.http.routers.backend.middlewares=limit@docker
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=0
      - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=2000
